# Generated by Django 3.2.6 on 2021-08-11 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOfBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('faction', models.CharField(max_length=64)),
                ('player_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('rp', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('points_or_pl', models.TextField(choices=[('POINTS', 'Points'), ('PL', 'PL')], default='PL', max_length=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('datasheet_name', models.CharField(max_length=128)),
                ('datasheet_source', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('HQ', 'HQ'), ('TROOPS', 'Troops'), ('ELITE', 'Elite'), ('FA', 'Fast Attack'), ('FLYER', 'Flyer'), ('HS', 'Heavy Support'), ('FORTIFICATION', 'Fortification'), ('LOW', 'Lord of War'), ('DT', 'Dedicated Transport'), ('NS', 'No Slot')], default='HQ', max_length=16)),
                ('points', models.IntegerField()),
                ('model_count', models.IntegerField()),
                ('is_character', models.BooleanField()),
                ('is_psyker', models.BooleanField()),
                ('is_battle_ready', models.BooleanField()),
                ('is_exp_ineligible', models.BooleanField()),
                ('description', models.TextField()),
                ('other_rules', models.TextField()),
                ('exp_adjustment', models.IntegerField()),
                ('cp_adjustment', models.IntegerField()),
                ('oob', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crusade.orderofbattle')),
            ],
        ),
        migrations.CreateModel(
            name='UnitUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crusade.unit')),
            ],
        ),
    ]
